# Default win-run aliases
# These are sensible defaults that most users might want
aliases:
  # Example aliases - users should customize these in ~/.config/wslutil/win-run.yml
  # brave.exe:
  #   path: ${WIN_PROGRAMFILES}/BraveSoftware/Brave-Browser/Application/brave.exe
  #   options: null
  # notepad++.exe:
  #   path: ${WIN_PROGRAMFILES}/Notepad++/notepad++.exe
  #   options: null